### ISSUE TITLE
Client perspective

### ISSUE THREAD

**Issue by Jkutkut** [jkutkutOrg/EatUp#1]

**Comment by alexeses** [comment]
Hi team!

To have a functional version and start working optimally, I was thinking of the following:

1. The user authentication system based on email/password will not exist, this will be replaced by reading a **QR CODE** that the user will have at the table. When opening the APP, the user will be asked to turn on the camera or **manually enter** the **code** if the QR or mobile camera fails. *See section 1.1
2. Once the QR code is scanned or the code is manually entered, the user will access the screen to select all the dishes they want to order (one or several dishes per category...). *See section 2.1
3. After selecting the dishes and confirming the selection, the user will move to the screen to confirm the order and pay for it to be sent to the kitchen. *See section 3.1
4. The user will have full access to review their orders in progress and/or completed. (_HOW DO WE STORE THE ORDERS IF WE DO NOT HAVE A UNIQUE ID PER CLIENT?_ [Chat GPT moment: How to get IMEI or ID mobile from app](https://stackoverflow.com/questions/2785485/is-there-a-unique-android-device-id))

<details><summary>1.1</summary>
In my opinion, this is the smartest option since we save the authentication system and the listing of free/occupied tables.

If the user has a camera-enabled terminal and/or functional, from the application they can scan the QR code that must be unique to the table. If they do not have a camera or have problems, the user can manually enter the code and follow the ordering process.

The QR code should not be anything complex, since we are talking about unique codes for each local/table, for example: SUMO-00-001 // (restaurant initials)-(restaurant id)-(table).

Based on this generated code, we can make a direct communication with the backend and send all the necessary information to process the order.
</details> 

<details><summary>2.1</summary>
The product screen will be interactive with the possibility of selecting one or several products with a product search engine and categories/sections for the different dishes.

This step may seem trivial, but it is VERY IMPORTANT to create dishes with as much information as possible:
- Name
- Image associated with the dish
- Description
- Section: Starter, Side dish, Main dish, Dessert, Drink...
- And much more: Among us all, we must provide data to categorize the dishes in a very simple way.
</details> 

<details><summary>3.1</summary>
For now, as we do not have a payment system, we will simulate the payment and the order will go to the kitchen.
</details> 

Regarding the databases:
Instead of having unique users, we will have unique device IDs, which will be automatically registered in the database when the QR code is scanned.

Each unique customer identifier will store sessions (with a timestamp of the scan time, for example), and based on this data, we will add attributes to the datababase. What do you think? The only problem is figuring out if we can obtain the unique mobile device identifier.

Please, I am open to modifications and feedback from your side, the clearer we all have it, the better. The task is not finished yet, we must create a design base for the interfaces.

**Comment by Jkutkut** [comment]
Added to the wiki
